import csv
import os

csv_file_path = r'c:\Users\Practicas\Local Sites\findbuy\app\public\wp-content\plugins\findbuy-core\lista-codigos-postales-espana.csv'

# New data to add
new_entries_raw = """
28001;BARRIO_DE_SALAMANCA;MADRID;MADRID;COMUNIDAD_DE_MADRID
28004;MALASAÑA;MADRID;MADRID;COMUNIDAD_DE_MADRID
28013;CENTRO;MADRID;MADRID;COMUNIDAD_DE_MADRID
28040;CIUDAD_UNIVERSITARIA;MADRID;MADRID;COMUNIDAD_DE_MADRID
28050;LAS_TABLAS;MADRID;MADRID;COMUNIDAD_DE_MADRID
08001;EL_RAVAL;BARCELONA;BARCELONA;CATALUÑA
08002;BARRI_GOTIC;BARCELONA;BARCELONA;CATALUÑA
08015;EIXAMPLE_ESQUERRA;BARCELONA;BARCELONA;CATALUÑA
08021;SANT_GERVASI;BARCELONA;BARCELONA;CATALUÑA
08028;LES_CORTS;BARCELONA;BARCELONA;CATALUÑA
46001;CIUTAT_VELLA;VALENCIA;VALENCIA;COMUNIDAD_VALENCIANA
46002;CENTRO;VALENCIA;VALENCIA;COMUNIDAD_VALENCIANA
46010;BENIMACLET;VALENCIA;VALENCIA;COMUNIDAD_VALENCIANA
46018;PATRAIX;VALENCIA;VALENCIA;COMUNIDAD_VALENCIANA
41001;CASCO_ANTIGUO;SEVILLA;SEVILLA;ANDALUCÍA
41004;SANTA_CRUZ;SEVILLA;SEVILLA;ANDALUCÍA
41007;NERVIÓN;SEVILLA;SEVILLA;ANDALUCÍA
41012;LOS_REMEDIOS;SEVILLA;SEVILLA;ANDALUCÍA
50001;CASCO_HISTORICO;ZARAGOZA;ZARAGOZA;ARAGÓN
50004;CENTRO;ZARAGOZA;ZARAGOZA;ARAGÓN
50009;UNIVERSIDAD;ZARAGOZA;ZARAGOZA;ARAGÓN
50018;ACTUR;ZARAGOZA;ZARAGOZA;ARAGÓN
29001;CENTRO_HISTORICO;MALAGA;MALAGA;ANDALUCÍA
29007;CARRANQUE;MALAGA;MALAGA;ANDALUCÍA
29010;TEATINOS;MALAGA;MALAGA;ANDALUCÍA
29016;EL_LIMONAR;MALAGA;MALAGA;ANDALUCÍA
48001;CASCO_VIEJO;BILBAO;BIZKAIA;PAÍS_VASCO
48009;ABANDO;BILBAO;BIZKAIA;PAÍS_VASCO
48012;INDAUTXU;BILBAO;BIZKAIA;PAÍS_VASCO
48015;DEUSTO;BILBAO;BIZKAIA;PAÍS_VASCO
07001;CASCO_ANTIGUO;PALMA;ILLES_BALEARS;ILLES_BALEARS
07002;SANTA_CATALINA;PALMA;ILLES_BALEARS;ILLES_BALEARS
07011;SON_ESPANYOLET;PALMA;ILLES_BALEARS;ILLES_BALEARS
35001;VEGUETA;LAS_PALMAS_DE_GRAN_CANARIA;LAS_PALMAS;CANARIAS
35004;TRIANA;LAS_PALMAS_DE_GRAN_CANARIA;LAS_PALMAS;CANARIAS
35010;LAS_CANTERAS;LAS_PALMAS_DE_GRAN_CANARIA;LAS_PALMAS;CANARIAS
03001;CENTRO;ALICANTE;ALICANTE;COMUNIDAD_VALENCIANA
14001;CASCO_HISTORICO;CORDOBA;CORDOBA;ANDALUCÍA
15001;CIUDAD_VIEJA;A_CORUÑA;A_CORUÑA;GALICIA
18001;CENTRO;GRANADA;GRANADA;ANDALUCÍA
20003;PARTE_VIEJA;SAN_SEBASTIAN;GIPUZKOA;PAÍS_VASCO
33001;CENTRO;OVIEDO;ASTURIAS;ASTURIAS
36201;CASCO_URBANO;VIGO;PONTEVEDRA;GALICIA
47001;CENTRO;VALLADOLID;VALLADOLID;CASTILLA_Y_LEÓN
"""

# Parse new entries into a dictionary {cp: line}
new_entries = {}
for line in new_entries_raw.strip().split('\n'):
    if line.strip():
        parts = line.strip().split(';')
        if len(parts) >= 1:
            new_entries[parts[0]] = line.strip()

# Read existing CPs
existing_cps = set()
with open(csv_file_path, 'r', encoding='latin1', errors='replace') as f:
    for line in f:
        parts = line.strip().split(';')
        if len(parts) >= 1:
            existing_cps.add(parts[0])

# Determine what to add
to_add = []
for cp, line in new_entries.items():
    if cp not in existing_cps:
        to_add.append(line)

# Append to file
if to_add:
    with open(csv_file_path, 'a', encoding='latin1', newline='') as f:
        # Check if file ends with newline
        # Not easily doable without reading end, but distinct write helps
        f.write('\n') 
        for line in to_add:
            f.write(line + '\n')
    print(f"Added {len(to_add)} new entries.")
else:
    print("No new entries to add (all duplicates).")
